# Generated by Django 5.2.4 on 2025-07-16 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairrent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordreview',
            name='property_address',
            field=models.CharField(default=datetime.datetime(2025, 7, 16, 22, 23, 9, 978539, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='cleanliness',
            field=models.CharField(blank=True, choices=[('very_tidy', 'Very Tidy'), ('average', 'Average'), ('relaxed', 'Relaxed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='lifestyle_preferences',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='sleep_schedule',
            field=models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('flexible', 'Flexible')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2025-07-16'),
            preserve_default=False,
        ),
    ]
