# Generated by Django 5.2.4 on 2025-07-18 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairrent_app', '0003_rentcheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user_name', models.CharField(max_length=255)),
                ('liked_user_age', models.IntegerField(blank=True, null=True)),
                ('liked_user_gender', models.CharField(blank=True, max_length=100)),
                ('liked_user_location', models.CharField(blank=True, max_length=255)),
                ('liked_user_budget', models.IntegerField(blank=True, null=True)),
                ('liked_user_bio', models.TextField(blank=True)),
                ('liked_user_compatibility_score', models.IntegerField(blank=True, null=True)),
                ('liked_user_avatar_url', models.URLField(blank=True, max_length=500)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
