# Generated by Django 5.2.4 on 2025-07-20 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairrent_app', '0005_rentalcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentDeclarationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
                ('bedrooms', models.CharField(max_length=10)),
                ('actual_rent_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('council_tax_band', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_council_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discrepancy_found', models.BooleanField(default=False)),
                ('analysis_result', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_declaration_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
