# Generated by Django 5.2.4 on 2025-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairrent_app', '0007_likedprofile_liked_user_uid_roommateprofile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_uid', models.CharField(db_index=True, max_length=255)),
                ('receiver_uid', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='likedprofile',
            name='liked_user_uid',
            field=models.CharField(blank=True, help_text='Unique ID (Django PK or UUID) of the liked user.', max_length=255, null=True, unique=True),
        ),
    ]
