# Generated by Django 5.2.4 on 2025-07-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairrent_app', '0009_alter_likedprofile_liked_user_uid_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='availability_date',
            field=models.DateField(blank=True, help_text='Date room becomes available', null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='house_rules',
            field=models.TextField(blank=True, help_text="Comma-separated house rules (e.g., 'No pets, Quiet after 10 PM')", null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='num_available_rooms',
            field=models.IntegerField(blank=True, help_text='Number of rooms available in your property.', null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='property_photos',
            field=models.TextField(blank=True, help_text='Comma-separated URLs of property photos', null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='rent_amount_offering',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent per room (if offering)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='room_size',
            field=models.CharField(blank=True, help_text="e.g., 'Double', 'Single', 'En-suite'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('looking_for_room', 'Looking for a Room'), ('offering_room', 'Offering a Room')], help_text='Are you looking for a room or offering one?', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="Tell us about yourself and what you're looking for/offering.", null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max monthly budget for a room (if looking)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Desired location (if looking) or property location (if offering)', max_length=255, null=True),
        ),
    ]
