# Generated by Django 5.2.4 on 2025-07-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairrent_app', '0010_roommateprofile_availability_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('looking_for_room', 'Looking for a Room'), ('offering_room', 'Offering a Room')], help_text='Type of the liked user (Looking for a Room / Offering a Room).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='bills_included',
            field=models.CharField(blank=True, help_text='Are bills included? (Yes, No)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='contact',
            field=models.CharField(blank=True, help_text='Contact email or phone number.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='furnished',
            field=models.CharField(blank=True, help_text='Is the room furnished? (Yes, No, Partially)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roommateprofile',
            name='occupation',
            field=models.CharField(blank=True, help_text='Your occupation.', max_length=255, null=True),
        ),
    ]
